### ISSUE TITLE
Compatibility between generate and publish

### ISSUE THREAD

**Issue by jgse** [eiffel-community/eiffel-remrem#10]
### Description
The release of generate and publish is in independent life cycle, but there are dependencies to consider
1. they both depends on semantics library. 
2. publish depends on generate

Is there any recommended combination of generate and publish version?
Is it OK to combine generate and publish with  different semantics version?

### Motivation
A compatibility list should be recommended at least so that user can use the right combination.

**Comment by z-sztrom** [comment]
As I know, new releases of both generate and publish services are provided whenever a new release of semantics library is available, so the latest releases are always compatible.

However, it's a good idea to create a list of recommended generate-publish pairs.
