### ISSUE TITLE
Dockerized remrem setup

### ISSUE THREAD

**Issue by Andrey9kin** [eiffel-community/eiffel-remrem#3]
@d-stahl-ericsson @danielyinanc @p-backman-ericsson @rogpers-ericsson 

While playing around with remrem I prepared dockerized setup that would allow new users to easily roll out remrem and try it out

https://github.com/Praqma/eiffel-remrem-docker

It includes all services, rabbit mq instance and nginx for load balancing/ingress traffic termination.
All could be created and loaded using one command - see documentation. Also, setup allows programmatically up-scale and down-scale services. If you scale up more than one instance then Docker and nginx will automatically load balance all incoming requests.

You are very welcome to leave issues or submit pull requests if you find and issue or want something to be added.

I hope it will be useful for you and your users

P.S.

I hope you don't mind that I'm using issues as discussion forum :) Otherwise, you might consider creating google group mailing list so we can move all discussions there ;)

**Comment by d-stahl-ericsson** [comment]
Awesome. Will check it out when I get the chance...

And no, we don't mind. Please keep discussing :)

**Comment by SantoshNC68** [comment]
@Andrey9kin  we have the docker setup for remrem in place now, do you think this is still valid? If you still think, then I would suggest you to open the tickets in corresponding repositories. This repository seems very isolated and will be cleaned up so as to make it more simpler and easier to read.

**Comment by Andrey9kin** [comment]
I do not support that setup anylonger. So it is fine to just skip it

**Comment by SantoshNC68** [comment]
Ok. Closing this issue
